"""remove_outcome_notes_field

Revision ID: 18d4e4920609
Revises: 2c7da2d48921
Create Date: 2026-01-11 16:13:32.926456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d4e4920609'
down_revision: Union[str, Sequence[str], None] = '2c7da2d48921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'outcome_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('outcome_notes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
