"""add_user_id_to_decisions

Revision ID: 7e8d39f70fa2
Revises: 18d4e4920609
Create Date: 2026-01-12 08:21:24.470926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7e8d39f70fa2'
down_revision: Union[str, Sequence[str], None] = '18d4e4920609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Demo user ID (same as in server/core/auth.py)
    DEMO_USER_ID = "00000000-0000-0000-0000-000000000001"
    
    # Add user_id column as nullable first
    op.add_column('decisions', sa.Column('user_id', postgresql.UUID(), nullable=True))
    
    # Set demo user_id for all existing records
    op.execute(f"UPDATE decisions SET user_id = '{DEMO_USER_ID}' WHERE user_id IS NULL")
    
    # Now make it non-nullable
    op.alter_column('decisions', 'user_id', existing_type=postgresql.UUID(), nullable=False)
    
    # Add index
    op.create_index(op.f('ix_decisions_user_id'), 'decisions', ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjust! ###
    op.drop_index(op.f('ix_decisions_user_id'), table_name='decisions')
    op.drop_column('decisions', 'user_id')
    # ### end Alembic commands ###
